Python 3.13 in slim

diff --git a/Dockerfile.slim b/Dockerfile.slim
--- a/Dockerfile.slim
+++ b/Dockerfile.slim
@@ -1,41 +1,53 @@
 # Dockerfile.slim
-# version: 24.9.1
+# version: 24.10.31
 
-# start with slim version
-FROM python:3.12-slim
+# Use Python image slim version
+FROM python:3.13-slim
 LABEL org.opencontainers.image.authors="Riverbed Community"
 LABEL org.opencontainers.image.source="https://github.com/riverbed/steelscript"
 
-RUN set -ex \
-        && install=' \
-                git \
-                less \
-                vim \
-                libpcap-dev \
-        ' \
-        && apt-get update && apt-get install -y $install --no-install-recommends && rm -rf /var/lib/apt/lists/*
-
+# Install deps for build
 RUN set -ex \
         && buildDeps=' \
+                git \
                 g++ \
-                libssl-dev \
-                libffi-dev \
+                libpcap-dev \
         ' \
-        && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
-        \
+        && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/*
+
+# Install SteelScript and modules
+RUN set -ex \        
+        && pip install --no-cache-dir --upgrade pip \
         && pip install --src /src \
-            -e git+https://github.com/riverbed/steelscript#egg=steelscript \
-            -e git+https://github.com/riverbed/steelscript-netprofiler#egg=steelscript-netprofiler \
-            -e git+https://github.com/riverbed/steelscript-wireshark#egg=steelscript-wireshark \
-            -e git+https://github.com/riverbed/steelscript-cmdline#egg=steelscript-cmdline \
-            -e git+https://github.com/riverbed/steelscript-scc#egg=steelscript-scc \
-            -e git+https://github.com/riverbed/steelscript-appresponse#egg=steelscript-appresponse \
-            -e git+https://github.com/riverbed/steelscript-netim.git#egg=steelscript-netim \
-            -e git+https://github.com/riverbed/steelscript-client-accelerator-controller#egg=steelscript-cacontroller \            
-        && pip install Cython \
-        && pip install --src /src \
-            -e git+https://github.com/riverbed/steelscript-steelhead#egg=steelscript-steelhead \
-            -e git+https://github.com/riverbed/steelscript-packets.git@master#egg=steelscript-packets \
-        && rm -f /src/pip-delete-this-directory.txt \
-        && apt-get purge -y --auto-remove $buildDeps \
+        -e git+https://github.com/riverbed/steelscript#egg=steelscript \
+        -e git+https://github.com/riverbed/steelscript-netprofiler#egg=steelscript-netprofiler \
+        -e git+https://github.com/riverbed/steelscript-wireshark#egg=steelscript-wireshark \
+        -e git+https://github.com/riverbed/steelscript-cmdline#egg=steelscript-cmdline \
+        -e git+https://github.com/riverbed/steelscript-scc#egg=steelscript-scc \
+        -e git+https://github.com/riverbed/steelscript-appresponse#egg=steelscript-appresponse \
+        -e git+https://github.com/riverbed/steelscript-netim.git#egg=steelscript-netim \
+        -e git+https://github.com/riverbed/steelscript-client-accelerator-controller#egg=steelscript-cacontroller \            
+        -e git+https://github.com/riverbed/steelscript-steelhead#egg=steelscript-steelhead \
+        -e git+https://github.com/riverbed/steelscript-packets.git@master#egg=steelscript-packets
+
+# Cleanup, purging build deps
+RUN set -ex \
+        && distroExtra=' \
+                gcc \
+        ' \                
+        && apt-get remove -y --purge --autoremove  $buildDeps $distroExtra \
         && rm -rf ~/.cache
+
+# Create a non-root user and group
+ARG USERNAME=steelscript
+ARG GROUPNAME=$USERNAME
+ARG USER_ID=1000
+ARG GROUP_ID=$USER_ID
+RUN groupadd --gid $GROUP_ID $GROUPNAME && useradd --create-home --gid $GROUP_ID --uid $USER_ID $USERNAME
+
+# Create SteelScript workspace
+RUN set -ex && steel mkworkspace -d /home/steelscript/workspace        
+WORKDIR /home/steelscript/workspace
+
+# Configure container startup
+CMD ["/bin/bash"]
